[workspace]
resolver = "2"
members = ["rsecret"]
exclude = ["secret-rpc", "secret-grpc-gateway"]

[patch.crates-io]
secret-sdk-proto = { git = "https://github.com/kent-3/secret-rust", branch = "main" }
secretrs = { git = "https://github.com/kent-3/secret-rust", branch = "main" }
